import 'package:flutter/widgets.dart';

class AppLocalizations {
  const AppLocalizations(this.locale);

  final Locale locale;

  static const supportedLocales = [
    Locale('ko'),
    Locale('en'),
    Locale('zh'),
    Locale('ja'),
  ];

  static const LocalizationsDelegate<AppLocalizations> delegate =
      _AppLocalizationsDelegate();

  static AppLocalizations of(BuildContext context) {
    return Localizations.of<AppLocalizations>(context, AppLocalizations)!;
  }

  String get _lang => _localizedValues.containsKey(locale.languageCode)
      ? locale.languageCode
      : 'en';

  String t(String key) =>
      _localizedValues[_lang]?[key] ?? _localizedValues['en']![key] ?? key;

  String error(Object err) => '${t('error')}: $err';
  String dbError(String message, String path) =>
      '${t('dbError')}: $message\n${t('path')}: $path';
  String selectedVerses(String ref, int count) => t(
    'selectedVerses',
  ).replaceAll('{ref}', ref).replaceAll('{count}', '$count');
  String shareText(String text) => t('shareText').replaceAll('{text}', text);
  String addedBookmarks(int count) =>
      t('addedBookmarks').replaceAll('{count}', '$count');
  String noteTitle(String ref) => t('noteTitle').replaceAll('{ref}', ref);
  String editNoteTitle(String ref) =>
      t('editNoteTitle').replaceAll('{ref}', ref);
  String highlightAdded(String color) =>
      t('highlightAdded').replaceAll('{color}', colorLabel(color));
  String colorLabel(String color) => switch (color) {
    'yellow' => t('yellow'),
    'green' => t('green'),
    'red' => t('red'),
    _ => color,
  };
  String currentLanguageOnly({required bool commentary}) =>
      commentary ? t('activeCommentaryOnly') : t('activeTranslationOnly');
  String wholeLanguage(String language, {required bool commentary}) =>
      commentary
      ? t('allCommentariesForLanguage').replaceAll('{language}', language)
      : t('allTranslationsForLanguage').replaceAll('{language}', language);
  String unavailableLanguage(String language) =>
      t('unavailableInCurrentRange').replaceAll('{language}', language);
  String bookIntroductionTitle(String bookName) =>
      t('bookIntroductionTitle').replaceAll('{book}', bookName);
}

class _AppLocalizationsDelegate
    extends LocalizationsDelegate<AppLocalizations> {
  const _AppLocalizationsDelegate();

  @override
  bool isSupported(Locale locale) =>
      ['ko', 'en', 'zh', 'ja'].contains(locale.languageCode);

  @override
  Future<AppLocalizations> load(Locale locale) async =>
      AppLocalizations(locale);

  @override
  bool shouldReload(_AppLocalizationsDelegate old) => false;
}

extension AppLocalizationsX on BuildContext {
  AppLocalizations get l10n => AppLocalizations.of(this);
}

const _localizedValues = <String, Map<String, String>>{
  'en': {
    'appTitle': 'Love',
    'reader': 'Reader',
    'search': 'Search',
    'saved': 'Saved',
    'setting': 'Setting',
    'settings': 'Settings',
    'appearance': 'Appearance',
    'themeMode': 'Theme Mode',
    'system': 'System',
    'light': 'Light',
    'dark': 'Dark',
    'appLanguage': 'App Language',
    'readerFont': 'Reader Font',
    'sansSerif': 'Sans-Serif',
    'serif': 'Serif',

    'readerTypography': 'Reader Typography',
    'fontSize': 'Font Size',
    'lineSpacing': 'Line Spacing',
    'uiScale': 'UI Scale',
    'biblesCommentaries': 'Bibles & Commentaries',
    'activeBible': 'Active Bible',
    'selectBible': 'Select Bible',
    'loadingBible': 'Loading Bible...',
    'errorLoadingBible': 'Error loading Bible',
    'activeCommentary': 'Active Commentary',
    'noneOff': 'None (Off)',
    'turnOffCommentary': 'Turn off commentary',
    'loadingCommentary': 'Loading Commentary...',
    'errorLoadingCommentary': 'Error loading Commentary',
    'selectBibleTranslation': 'Select Bible Version',
    'searchByPack': 'Search by language, source, or name...',
    'noTranslationsFound': 'No versions found',
    'versions': 'versions',
    'selectCommentary': 'Select Commentary',
    'noCommentariesFound': 'No commentaries found',
    'noBibleSelected':
        'No Bible selected or installed.\nPlease go to Library and select a version.',
    'noActiveBibleDb':
        'No active Bible database.\nPlease select a version in settings.',
    'error': 'Error',
    'dbError': 'DB Error',
    'path': 'Path',
    'unknownBible': 'Unknown Bible',
    'bible': 'Bible',
    'toggleCommentary': 'Toggle Commentary',
    'selectBookChapter': 'Select Book & Chapter',
    'oldTestament': 'Old\nTestament',
    'newTestament': 'New\nTestament',
    'commentaryError': 'Commentary Error',
    'noCommentaryForChapter': 'No commentary available for this chapter.',
    'checkAnotherCommentaryDatabase': 'Check another commentary database',
    'searchingCommentaryDatabases': 'Searching commentary databases...',
    'otherCommentariesFound':
        '{count} commentary database(s) have this chapter.',
    'noOtherCommentaryForChapter':
        'No other commentary database has commentary for this chapter.',
    'switchToCommentary': 'Switch to commentary',
    'chapterIntro': 'Chapter intro / overview',
    'verseLabel': 'v.',
    'viewIntro': 'View introduction',
    'exitFullscreen': 'Exit fullscreen',
    'enterFullscreen': 'View fullscreen',
    'selectCommentaryToActivate': 'Select Commentary to Activate',
    'noIntroInfo':
        'This commentary has no introduction or background information.',
    'introAndInfo': 'Introduction & Info',
    'bookIntroductionTitle': 'About {book}',
    'bookmarks': 'Bookmarks',
    'highlights': 'Highlights',
    'notes': 'Notes',
    'noBookmarks': 'No bookmarks saved yet.',
    'noHighlights': 'No highlights saved yet.',
    'noNotes': 'No notes saved yet.',
    'verseTextNotFound': '[Verse text not found in current version]',
    'versesNotFound': '[Verses not found in current version]',
    'bookmarkRemoved': 'Bookmark removed.',
    'highlightRemoved': 'Highlight removed.',
    'noteDeleted': 'Note deleted.',
    'noteUpdated': 'Note updated.',
    'editNoteTitle': 'Edit note ({ref})',
    'noteTitle': 'Write note ({ref})',
    'noteHint': 'Write a note or reflection for this verse...',
    'cancel': 'Cancel',
    'save': 'Save',
    'searchVerseText': 'Search verse text...',
    'allBible': 'All Bible',
    'ot': 'OT',
    'nt': 'NT',
    'commentary': 'Commentary',
    'languageRange': 'Language range:',
    'activeTranslationOnly': 'Active version only',
    'activeCommentaryOnly': 'Active commentary only',
    'unavailableInCurrentRange': '{language} (not in current range)',
    'allTranslationsForLanguage': 'All {language} versions',
    'allCommentariesForLanguage': 'All {language} commentaries',
    'noActiveCommentary':
        'No commentary selected.\nPlease choose one in Settings/Library.',
    'noHits': 'No hits',
    'commentaryPrefix': 'Commentary',
    'selectedVerses': '{ref} selected ({count})',
    'copyToClipboard': 'Copy to clipboard',
    'copiedToClipboard': 'Copied to clipboard.',
    'share': 'Share',
    'shareText': 'Share: {text}',
    'removeBookmark': 'Remove bookmark',
    'addBookmark': 'Add bookmark',
    'addedBookmarks': '{count} verse(s) added to bookmarks.',
    'highlightRemove': 'Remove highlight',
    'highlightAdd': 'Highlight',
    'highlightAdded': '{color} highlight added.',
    'viewCommentary': 'View commentary',
    'writeEditNote': 'Write/Edit note',
    'yellow': 'yellow',
    'green': 'green',
    'red': 'red',
    'korean': 'Korean',
    'english': 'English',
    'simplifiedChinese': 'Chinese (Simplified)',
    'japanese': 'Japanese',
  },
  'ko': {
    'appTitle': 'Love',
    'reader': '읽기',
    'search': '검색',
    'saved': '저장',
    'setting': '설정',
    'settings': '설정',
    'appearance': '화면',
    'themeMode': '테마 모드',
    'system': '시스템',
    'light': '라이트',
    'dark': '다크',
    'appLanguage': '앱 언어',
    'readerFont': '리더 글꼴',
    'sansSerif': '고딕',
    'serif': '명조',

    'readerTypography': '리더 글자 설정',
    'fontSize': '글자 크기',
    'lineSpacing': '줄 간격',
    'uiScale': 'UI 크기',
    'biblesCommentaries': '성경 및 주석',
    'activeBible': '현재 성경',
    'selectBible': '성경 선택',
    'loadingBible': '성경 불러오는 중...',
    'errorLoadingBible': '성경 불러오기 오류',
    'activeCommentary': '현재 주석',
    'noneOff': '없음 (꺼짐)',
    'turnOffCommentary': '주석 끄기',
    'loadingCommentary': '주석 불러오는 중...',
    'errorLoadingCommentary': '주석 불러오기 오류',
    'selectBibleTranslation': '성경 판본 선택',
    'searchByPack': '언어, 출처, 이름으로 검색...',
    'noTranslationsFound': '판본을 찾을 수 없습니다',
    'versions': '개 판본',
    'selectCommentary': '주석 선택',
    'noCommentariesFound': '주석을 찾을 수 없습니다',
    'noBibleSelected': '선택되거나 설치된 성경이 없습니다.\n라이브러리에서 판본을 선택해주세요.',
    'noActiveBibleDb': '활성 성경 데이터베이스가 없습니다.\n설정에서 판본을 선택해주세요.',
    'error': '오류',
    'dbError': 'DB 오류',
    'path': '경로',
    'unknownBible': '알 수 없는 성경',
    'bible': '성경',
    'toggleCommentary': '주석 켜기/끄기',
    'selectBookChapter': '책과 장 선택',
    'oldTestament': '구약',
    'newTestament': '신약',
    'commentaryError': '주석 오류',
    'noCommentaryForChapter': '이 장에 대한 주석이 없습니다.',
    'checkAnotherCommentaryDatabase': '다른 주석 데이터베이스 확인',
    'searchingCommentaryDatabases': '주석 데이터베이스 검색 중...',
    'otherCommentariesFound': '이 장의 주석이 있는 데이터베이스 {count}개를 찾았습니다.',
    'noOtherCommentaryForChapter': '다른 주석 데이터베이스에도 이 장의 주석이 없습니다.',
    'switchToCommentary': '주석으로 전환',
    'chapterIntro': '장의 서론 / 개요',
    'verseLabel': '절',
    'viewIntro': '서론 및 소개 보기',
    'exitFullscreen': '전체화면 종료',
    'enterFullscreen': '전체화면으로 보기',
    'selectCommentaryToActivate': '활성화할 주석 선택',
    'noIntroInfo': '이 주석에는 서론 및 배경 설명 정보가 없습니다.',
    'introAndInfo': '서론 및 소개',
    'bookIntroductionTitle': '{book} 소개',
    'bookmarks': '북마크',
    'highlights': '하이라이트',
    'notes': '노트',
    'noBookmarks': '저장된 북마크가 없습니다.',
    'noHighlights': '저장된 하이라이트가 없습니다.',
    'noNotes': '저장된 노트가 없습니다.',
    'verseTextNotFound': '[현재 판본에서 구절을 찾을 수 없습니다]',
    'versesNotFound': '[현재 판본에서 구절들을 찾을 수 없습니다]',
    'bookmarkRemoved': '북마크가 제거되었습니다.',
    'highlightRemoved': '하이라이트가 제거되었습니다.',
    'noteDeleted': '노트가 삭제되었습니다.',
    'noteUpdated': '노트가 수정되었습니다.',
    'editNoteTitle': '노트 수정 ({ref})',
    'noteTitle': '노트 작성 ({ref})',
    'noteHint': '여기에 구절에 대한 주석이나 묵상을 적어보세요...',
    'cancel': '취소',
    'save': '저장',
    'searchVerseText': '구절 텍스트 검색...',
    'allBible': '성경 전체',
    'ot': '구약',
    'nt': '신약',
    'commentary': '주석',
    'languageRange': '언어 범위:',
    'activeTranslationOnly': '현재 설정된 판본만',
    'activeCommentaryOnly': '현재 설정된 주석만',
    'unavailableInCurrentRange': '{language} (현재 범위에 없음)',
    'allTranslationsForLanguage': '{language} 판본 전체',
    'allCommentariesForLanguage': '{language} 주석 전체',
    'noActiveCommentary': '선택된 주석이 없습니다.\n설정/라이브러리에서 주석을 선택해주세요.',
    'noHits': '검색 결과 없음',
    'commentaryPrefix': '주석',
    'selectedVerses': '{ref} 선택됨 ({count}개)',
    'copyToClipboard': '클립보드에 복사',
    'copiedToClipboard': '클립보드에 복사되었습니다.',
    'share': '공유하기',
    'shareText': '공유: {text}',
    'removeBookmark': '북마크에서 제거',
    'addBookmark': '북마크에 추가',
    'addedBookmarks': '{count}개의 구절이 북마크에 추가되었습니다.',
    'highlightRemove': '하이라이트 제거',
    'highlightAdd': '형광펜 하이라이트',
    'highlightAdded': '형광펜 하이라이트({color})가 추가되었습니다.',
    'viewCommentary': '주석 보기',
    'writeEditNote': '노트 작성 및 수정',
    'yellow': '노란색',
    'green': '초록색',
    'red': '빨간색',
    'korean': '한국어',
    'english': '영어',
    'simplifiedChinese': '중국어(간체)',
    'japanese': '일본어',
  },
  'zh': {
    'appTitle': 'Love',
    'reader': '阅读',
    'search': '搜索',
    'saved': '保存',
    'setting': '设置',
    'settings': '设置',
    'appearance': '外观',
    'themeMode': '主题模式',
    'system': '系统',
    'light': '浅色',
    'dark': '深色',
    'appLanguage': '应用语言',
    'readerFont': '阅读字体',
    'sansSerif': '无衬线',
    'serif': '衬线',

    'readerTypography': '阅读排版',
    'fontSize': '字体大小',
    'lineSpacing': '行距',
    'uiScale': '界面缩放',
    'biblesCommentaries': '圣经与注释',
    'activeBible': '当前圣经',
    'selectBible': '选择圣经',
    'loadingBible': '正在加载圣经...',
    'errorLoadingBible': '加载圣经出错',
    'activeCommentary': '当前注释',
    'noneOff': '无（关闭）',
    'turnOffCommentary': '关闭注释',
    'loadingCommentary': '正在加载注释...',
    'errorLoadingCommentary': '加载注释出错',
    'selectBibleTranslation': '选择圣经版本',
    'searchByPack': '按语言、来源或名称搜索...',
    'noTranslationsFound': '未找到版本',
    'versions': '个版本',
    'selectCommentary': '选择注释',
    'noCommentariesFound': '未找到注释',
    'noBibleSelected': '未选择或安装圣经。\n请到资料库选择版本。',
    'noActiveBibleDb': '没有当前圣经数据库。\n请在设置中选择版本。',
    'error': '错误',
    'dbError': '数据库错误',
    'path': '路径',
    'unknownBible': '未知圣经',
    'bible': '圣经',
    'toggleCommentary': '切换注释',
    'selectBookChapter': '选择书卷与章节',
    'oldTestament': '旧约',
    'newTestament': '新约',
    'commentaryError': '注释错误',
    'noCommentaryForChapter': '本章暂无注释。',
    'checkAnotherCommentaryDatabase': '检查其他注释数据库',
    'searchingCommentaryDatabases': '正在搜索注释数据库...',
    'otherCommentariesFound': '找到 {count} 个包含本章注释的数据库。',
    'noOtherCommentaryForChapter': '其他注释数据库也没有本章注释。',
    'switchToCommentary': '切换到注释',
    'chapterIntro': '本章导言 / 概览',
    'verseLabel': '节',
    'viewIntro': '查看导言',
    'exitFullscreen': '退出全屏',
    'enterFullscreen': '全屏查看',
    'selectCommentaryToActivate': '选择要启用的注释',
    'noIntroInfo': '此注释没有导言或背景信息。',
    'introAndInfo': '导言与信息',
    'bookIntroductionTitle': '关于{book}',
    'bookmarks': '书签',
    'highlights': '高亮',
    'notes': '笔记',
    'noBookmarks': '尚无书签。',
    'noHighlights': '尚无高亮。',
    'noNotes': '尚无笔记。',
    'verseTextNotFound': '[当前版本中找不到经文]',
    'versesNotFound': '[当前版本中找不到经文]',
    'bookmarkRemoved': '书签已移除。',
    'highlightRemoved': '高亮已移除。',
    'noteDeleted': '笔记已删除。',
    'noteUpdated': '笔记已更新。',
    'editNoteTitle': '编辑笔记（{ref}）',
    'noteTitle': '写笔记（{ref}）',
    'noteHint': '为这节经文写下笔记或默想...',
    'cancel': '取消',
    'save': '保存',
    'searchVerseText': '搜索经文...',
    'allBible': '全部圣经',
    'ot': '旧约',
    'nt': '新约',
    'commentary': '注释',
    'languageRange': '语言范围：',
    'activeTranslationOnly': '仅当前版本',
    'activeCommentaryOnly': '仅当前注释',
    'unavailableInCurrentRange': '{language}（当前范围不可用）',
    'allTranslationsForLanguage': '全部 {language} 版本',
    'allCommentariesForLanguage': '全部 {language} 注释',
    'noActiveCommentary': '未选择注释。\n请在设置/资料库中选择注释。',
    'noHits': '无结果',
    'commentaryPrefix': '注释',
    'selectedVerses': '已选择 {ref}（{count}）',
    'copyToClipboard': '复制到剪贴板',
    'copiedToClipboard': '已复制到剪贴板。',
    'share': '分享',
    'shareText': '分享：{text}',
    'removeBookmark': '移除书签',
    'addBookmark': '添加书签',
    'addedBookmarks': '已将 {count} 节加入书签。',
    'highlightRemove': '移除高亮',
    'highlightAdd': '高亮',
    'highlightAdded': '已添加{color}高亮。',
    'viewCommentary': '查看注释',
    'writeEditNote': '写/编辑笔记',
    'yellow': '黄色',
    'green': '绿色',
    'red': '红色',
    'korean': '韩语',
    'english': '英语',
    'simplifiedChinese': '中文（简体）',
    'japanese': '日语',
  },
  'ja': {
    'appTitle': 'Love',
    'reader': '読む',
    'search': '検索',
    'saved': '保存',
    'setting': '設定',
    'settings': '設定',
    'appearance': '表示',
    'themeMode': 'テーマモード',
    'system': 'システム',
    'light': 'ライト',
    'dark': 'ダーク',
    'appLanguage': 'アプリ言語',
    'readerFont': 'リーダーフォント',
    'sansSerif': 'ゴシック',
    'serif': '明朝',

    'readerTypography': 'リーダー文字設定',
    'fontSize': '文字サイズ',
    'lineSpacing': '行間',
    'uiScale': 'UIスケール',
    'biblesCommentaries': '聖書と注解',
    'activeBible': '現在の聖書',
    'selectBible': '聖書を選択',
    'loadingBible': '聖書を読み込み中...',
    'errorLoadingBible': '聖書の読み込みエラー',
    'activeCommentary': '現在の注解',
    'noneOff': 'なし（オフ）',
    'turnOffCommentary': '注解をオフ',
    'loadingCommentary': '注解を読み込み中...',
    'errorLoadingCommentary': '注解の読み込みエラー',
    'selectBibleTranslation': '聖書版を選択',
    'searchByPack': '言語、出典、名前で検索...',
    'noTranslationsFound': '版が見つかりません',
    'versions': '版',
    'selectCommentary': '注解を選択',
    'noCommentariesFound': '注解が見つかりません',
    'noBibleSelected': '聖書が選択またはインストールされていません。\nライブラリで版を選択してください。',
    'noActiveBibleDb': '有効な聖書データベースがありません。\n設定で版を選択してください。',
    'error': 'エラー',
    'dbError': 'DBエラー',
    'path': 'パス',
    'unknownBible': '不明な聖書',
    'bible': '聖書',
    'toggleCommentary': '注解を切り替え',
    'selectBookChapter': '書巻と章を選択',
    'oldTestament': '旧約',
    'newTestament': '新約',
    'commentaryError': '注解エラー',
    'noCommentaryForChapter': 'この章の注解はありません。',
    'checkAnotherCommentaryDatabase': '別の注解データベースを確認',
    'searchingCommentaryDatabases': '注解データベースを検索中...',
    'otherCommentariesFound': 'この章の注解があるデータベースが {count} 件あります。',
    'noOtherCommentaryForChapter': '他の注解データベースにもこの章の注解はありません。',
    'switchToCommentary': '注解に切り替え',
    'chapterIntro': '章の序論 / 概要',
    'verseLabel': '節',
    'viewIntro': '序論を見る',
    'exitFullscreen': '全画面を終了',
    'enterFullscreen': '全画面で表示',
    'selectCommentaryToActivate': '有効にする注解を選択',
    'noIntroInfo': 'この注解には序論や背景情報がありません。',
    'introAndInfo': '序論と情報',
    'bookIntroductionTitle': '{book}について',
    'bookmarks': 'ブックマーク',
    'highlights': 'ハイライト',
    'notes': 'ノート',
    'noBookmarks': '保存されたブックマークはありません。',
    'noHighlights': '保存されたハイライトはありません。',
    'noNotes': '保存されたノートはありません。',
    'verseTextNotFound': '[現在の版で聖句が見つかりません]',
    'versesNotFound': '[現在の版で聖句が見つかりません]',
    'bookmarkRemoved': 'ブックマークを削除しました。',
    'highlightRemoved': 'ハイライトを削除しました。',
    'noteDeleted': 'ノートを削除しました。',
    'noteUpdated': 'ノートを更新しました。',
    'editNoteTitle': 'ノートを編集（{ref}）',
    'noteTitle': 'ノートを書く（{ref}）',
    'noteHint': 'この聖句についてのノートや黙想を書いてください...',
    'cancel': 'キャンセル',
    'save': '保存',
    'searchVerseText': '聖句を検索...',
    'allBible': '聖書全体',
    'ot': '旧約',
    'nt': '新約',
    'commentary': '注解',
    'languageRange': '言語範囲:',
    'activeTranslationOnly': '現在の版のみ',
    'activeCommentaryOnly': '現在の注解のみ',
    'unavailableInCurrentRange': '{language}（現在の範囲にありません）',
    'allTranslationsForLanguage': '{language}版すべて',
    'allCommentariesForLanguage': '{language}注解すべて',
    'noActiveCommentary': '注解が選択されていません。\n設定/ライブラリで注解を選択してください。',
    'noHits': '結果なし',
    'commentaryPrefix': '注解',
    'selectedVerses': '{ref} を選択（{count}）',
    'copyToClipboard': 'クリップボードにコピー',
    'copiedToClipboard': 'クリップボードにコピーしました。',
    'share': '共有',
    'shareText': '共有: {text}',
    'removeBookmark': 'ブックマークから削除',
    'addBookmark': 'ブックマークに追加',
    'addedBookmarks': '{count}節をブックマークに追加しました。',
    'highlightRemove': 'ハイライトを削除',
    'highlightAdd': 'ハイライト',
    'highlightAdded': '{color}ハイライトを追加しました。',
    'viewCommentary': '注解を見る',
    'writeEditNote': 'ノート作成・編集',
    'yellow': '黄色',
    'green': '緑色',
    'red': '赤色',
    'korean': '韓国語',
    'english': '英語',
    'simplifiedChinese': '中国語（簡体字）',
    'japanese': '日本語',
  },
};
